# Generated by Django 5.2.5 on 2025-08-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsconfig',
            options={'verbose_name': 'News Config', 'verbose_name_plural': 'News Config'},
        ),
    ]
