# Generated by Django 5.2.5 on 2025-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_otp_expires_at_customuser_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_account',
            field=models.BooleanField(default=False),
        ),
    ]
